insert into CURRENCY_EXCHANGE( ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE)
values(101,'USD','INR',85);
insert into CURRENCY_EXCHANGE( ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE)
values(102,'EURO','INR',89.5);